/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smict.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 06-16-2015
 * 
 * XDoclet definition:
 * @struts.form name="mainForm"
 */
public class MainForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** login_id property */
	private String login_id;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the login_id.
	 * @return String
	 */
	public String getLogin_id() {
		return login_id;
	}

	/** 
	 * Set the login_id.
	 * @param login_id The login_id to set
	 */
	public void setLogin_id(String login_id) {
		this.login_id = login_id;
	}
}